WebApplication1/Models/Operation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Operation
    {
        public Operation() : this(id: 0, firstEvent: 0, secondEvent: 0,duration: 0) { }

        public Operation(int id, int firstEvent, int secondEvent,int duration)
        {
            Id = id;
            FirstEvent = firstEvent;
            SecondEvent = secondEvent;
            Duration = duration;
        }
        public int Id { get; set; }
        [Required(ErrorMessage = "Початкова подія необхідна")]
        public int FirstEvent { get; set; }
        [Required(ErrorMessage = "Кінцева подія необхідна")]
        public int SecondEvent { get; set; }
        [Required(ErrorMessage = "Тривалість необхідна до введення")]
        public int Duration { get; set; }

    }
}

WebApplication1/Controllers/CalculationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class CalculationController : Controller
    {
        // GET: Calculation
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Context;
using WebApplication1.Helpers;

namespace WebApplication1.Controllers
{
    public class GraphController : Controller
    {
        public ContextAdapter adapter = new ContextAdapter();
        public OperationHelper operationHelper = new OperationHelper();
        public TableBuilder tableBuilder = new TableBuilder();
        public GraphHelper graphHelper = new GraphHelper();
        // GET: Graph
        public ActionResult Index()
        {
            List<List<int>> list = tableBuilder.GetIndicatiorsOfWork(adapter.GetOperations());
            ViewBag.CriticalValue = tableBuilder.GetCriticalValue(list[1]);
            ViewBag.CriticalPath = tableBuilder.GetCriticalPath(adapter.GetOperations(),list[4],list[5]);
            ViewBag.Coordinates = graphHelper.GetCoordinates(adapter.GetOperations());
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }
        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
        
    }
}

WebApplication1/Controllers/OperationsController.cs
using System.Web.Mvc;
using WebApplication1.Models;
using System.Data;
using System.Data.SqlClient;
using WebApplication1.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApplication1.Helpers;

namespace WebApplication1.Controllers
{
    public class OperationsController : Controller
    {

        public ContextAdapter adapter = new ContextAdapter();
        public OperationHelper operationHelper = new OperationHelper();
        public TableBuilder tableBuilder = new TableBuilder();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Operations = adapter.GetOperations();
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(Operation operation)
        {
            if (ModelState.IsValid)
            {
                adapter.Create(operation);
                return null;
            }
            return View(operation);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            List<Operation> operations = adapter.GetOperations();
            Operation operation = operations.Find(o => o.Id == id);
            return View(operation);
        }

        [HttpPost]
        public ActionResult Edit(Operation operation)
        {
            if (ModelState.IsValid)
            {
                adapter.Update(operation);
                return null;
            }
            return View(operation);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            adapter.DeleteById(id);
           
            return RedirectToAction("Index", "Operations");
        }

        [HttpPost]
        public ActionResult ClearAll()
        {
            adapter.DeleteAll();
            return RedirectToAction("Index", "Operations");
        }
    }
}

WebApplication1/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Context;
using WebApplication1.Helpers;

namespace WebApplication1.Views.Operations
{
    public class TableController : Controller
    {
        public ContextAdapter adapter = new ContextAdapter();
        public OperationHelper operationHelper = new OperationHelper();
        public TableBuilder tableBuilder = new TableBuilder();

        public ActionResult Index()
        {
            var actions = adapter.GetOperations();

            ViewBag.Labels = tableBuilder.GetCodeLabels(actions);
            ViewBag.Durations = tableBuilder.GetDurations(actions);
            List<List<int>> list = tableBuilder.GetIndicatiorsOfWork(actions);
            ViewBag.DurationsRP = list[0];
            ViewBag.DurationsRZ = list[1];
            ViewBag.DurationsPZ = list[2];
            ViewBag.DurationsPP = list[3];
            ViewBag.DurationsP = list[4];
            ViewBag.DurationsB = list[5];

            return View();
        }
    }
}

WebApplication1/Views/Calculation/Index.cshtml
<div class="container">
    <div class="row">
        <div id="test"></div>
        <div class="col-lg-6 col-md-12 col-sm-12" id="tableDiv">

        </div>
        <div class="col-lg-6 col-md-12 col-sm-12" id="graphDiv">
        </div>
    </div>
</div>
<script>
    var graphUrl = "@Url.Action("Index", "Graph")";
    var tableUrl = "@Url.Action("Index", "Table")";
    $("#tableDiv").load(tableUrl, function () { });
    $.get(graphUrl, function (data) {
        document.getElementById("graphDiv").html = display(data);
    });
    var display = function (data) {
        console.log(eval(new String(data)));
    }


</script>

WebApplication1/Views/Graph/Index.cshtml
<script src="http://d3js.org/d3.v3.min.js"></script>
<body class="text-center">
    <div class="p-4">
        <script type="text/javascript">
        var height = 500,
            width = 600,
            margin = 50,
            coordinates = [];

            @if(ViewBag.Coordinates != null)
            {
                var list = ViewBag.Coordinates;
                for (int i = list.Count - 1; i >= 0; i--)
                {
                    <text>
                        coordinates.push({ x: @list[i].X, y: "@list[i].Y"});
                    </text>
                }
            }

            var svg = d3.select("body").append("svg")
                .attr("class", "axis")
                .attr("width", width)
                .attr("height", height);

            var xAxisLength = width - 2 * margin;
            var yAxisLength = height - 2 * margin;

            var scaleY = d3.scale.ordinal()
                .domain(coordinates.map(function (d) { return d.y; }))
                .rangeRoundBands([0, yAxisLength], 1);

            var scaleX = d3.scale.linear()
                .domain([0, @ViewBag.CriticalValue + 2])
                .range([0, xAxisLength]);

            var xAxis = d3.svg.axis()
                .scale(scaleX)
                .orient("bottom");

            var yAxis = d3.svg.axis()
                .scale(scaleY)
                .orient("left");

            svg.append("g")
                .attr("class", "x-axis")
                .attr("transform",
                    "translate(" + margin + "," + (height - margin) + ")")
                .call(xAxis);

            svg.append("g")
                .attr("class", "y-axis")
                .attr("transform",
                    "translate(" + margin + "," + margin + ")")
                .call(yAxis);

            d3.selectAll("g.x-axis g.tick")
                .append("line")
                .classed("grid-line", true)
                .attr("x1", 0)
                .attr("y1", 0)
                .attr("x2", 0)
                .attr("y2", - (height - 2 * margin));

            d3.selectAll("g.y-axis g.tick")
                .append("line")
                .classed("grid-line", true)
                .attr("x1", 0)
                .attr("y1", 0)
                .attr("x2", xAxisLength)
                .attr("y2", 0);

            createChart(coordinates, "steelblue", "usd");

            function createChart(coordinates, colorStroke, label) {
                criticalPath = [];

                @if(ViewBag.CriticalPath != null)
                {
                    var list = ViewBag.CriticalPath;
                    for (int i = 0; i < list.Count; i++)
                    {
                        <text>
                            criticalPath.push("@list[i]");
                        </text>
                    }
                }
                var g = svg.append("g");
                for (var i = 0; i < coordinates.length; i += 2) {
                    if (criticalPath.includes(coordinates[i].y)) {
                        g.append("line")
                            .attr("class", "plot")
                            .attr("x1", scaleX(coordinates[i].x) + margin)
                            .attr("y1", scaleY(coordinates[i].y) + margin)
                            .attr("x2", scaleX(coordinates[i + 1].x) + margin)
                            .attr("y2", scaleY(coordinates[i + 1].y) + margin)
                            .style({
                                "stroke-width": 5,
                                "stroke": colorStroke
                            });
                    } else {
                        g.append("line")
                            .attr("class", "plot")
                            .attr("x1", scaleX(coordinates[i].x) + margin)
                            .attr("y1", scaleY(coordinates[i].y) + margin)
                            .attr("x2", scaleX(coordinates[i + 1].x) + margin)
                            .attr("y2", scaleY(coordinates[i + 1].y) + margin)
                            .style({
                                "stroke-width": 2,
                                "stroke": colorStroke
                            });
                    }
                }

                g.append("text")
                .attr("x", width - margin/2)
                .attr("y", height - margin - 5)
                .attr("text-anchor", "end")
                .style("font-size", "11px")
                            .text("Тривалість");

                g.append("text")
                    .attr("x", width - margin / 2)
                    .attr("y", height - margin / 2)
                    .attr("text-anchor", "end")
                    .style({ "font-size": 11, "font-weight": "bold" })
                .text("Критичний шлях = " + ((@ViewBag.CriticalValue != null)? @ViewBag.CriticalValue : 0));

                g.append("text")
                .attr("x", margin + 15)
                .attr("y", margin - 10)
                .attr("text-anchor", "end")
                .style("font-size", "11px")
                            .text("Код роботи");

                g.append("text")
                    .attr("x", (width / 2))
                    .attr("y", margin - 10)
                    .attr("text-anchor", "middle")
                    .style("font-size", "22px")
                    .text("Графік прив'язки");

                svg.selectAll(".dot " + label)
                .data(coordinates)
                .enter().append("circle")
                .style("stroke", colorStroke)
                .style("fill", "white")
                .attr("class", "dot " + label)
                .attr("r", 3)
                .attr("cx", function (d) { return scaleX(d.x) + margin; })
                .attr("cy", function (d) { return scaleY(d.y) + margin; });
                };
        </script>
    </div>
</body>



    @*@{
        }
        <!DOCTYPE html>

        <html>
        <head>
            <script type="text/javascript" src="https://d3js.org/d3.v4.min.js"></script>
        </head>
        <body>

            <div class="row p-4 m-2 justify-content-center">
                <div class="col-12 text-center mt-2">
                    <canvas id="canvas"></canvas>
                </div>
            </div>
        </body>
        </html>
        <script>

            var canvas = document.getElementById('canvas');
            var context = canvas.getContext('2d');
            canvas.width = 640;
            canvas.height = 480;
            var nodes = [
                { id: 1, x: 50, y: 240, text: 'B1', childs: [2, 3, 4, 5] },
                { id: 2, x: 150, y: 400, text: 'B2', childs: [11, 12] },
                { id: 3, x: 150, y: 80, text: 'B3' },
                { id: 4, x: 150, y: 170, text: 'B4' },
                { id: 5, x: 150, y: 280, text: 'B5', childs: [6, 7, 8, 9, 10] },
                { id: 6, x: 300, y: 100, text: 'B6' },
                { id: 7, x: 300, y: 150, text: 'B7' },
                { id: 8, x: 300, y: 200, text: 'B8' },
                { id: 9, x: 300, y: 250, text: 'B9' },
                { id: 10, x: 300, y: 300, text: 'B10' },
                { id: 11, x: 300, y: 430, text: 'B11' },
                { id: 12, x: 300, y: 370, text: 'B12' }
            ];


            nodes.forEach(function (node) {
                drawNodes(node, nodes);
                drawTops(nodes);
            });

            function drawTops(nodes) {
                nodes.forEach(function (node) {
                    context.beginPath();
                    context.arc(node.x, node.y, 20, 0, 2 * Math.PI, true);
                    context.stroke();
                    context.fillStyle = "white";
                    context.fill();
                    context.fillStyle = "black";
                    context.fillText(node.text, node.x - 5, node.y + 3);
                    context.closePath();
                })
            }
            function drawNodes(params, nodes) {

                if (params.childs && params.childs.length) {
                    params.childs.forEach(function (id) {
                        if (params.id != id) {
                            var child = getNodeById({ id: id, nodes: nodes });
                            context.beginPath();
                            context.moveTo(params.x, params.y);
                            context.lineTo(child.x, child.y);
                            context.stroke();
                            context.closePath();
                        }
                    });
                }
            }

            function getNodeById(params) {
                var result;
                params.nodes.forEach(function (node) {
                    if (node.id == params.id) {
                        result = node;
                    }
                });
                return result;
            }
        </script>*@

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Operations/Create.cshtml
@model WebApplication1.Models.Operation
@{

    Layout = "";
    var ACTION_NAME = "Операція";
    var DURACTION = "Тривалість";
    var ADD_TITLE = "Добавити";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row justify-content-center">
            <div class="col-4 align-self-center text-center">
                <label class="text-primary">@ACTION_NAME</label>
            </div>
            <div class="col-4">
                @Html.EditorFor(model => model.FirstEvent, new { htmlAttributes = new { @class = "form-control", id = "FirstEvent", @min = "1" } })
                @Html.ValidationMessageFor(model => model.FirstEvent, "", new { @class = "text-danger" })
            </div>
            <div class="col-4">
                @Html.EditorFor(model => model.SecondEvent, new { htmlAttributes = new { @class = "form-control", id = "SecondEvent", @min = "1" } })
                @Html.ValidationMessageFor(model => model.SecondEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row justify-content-center mt-1">
            <div class="col-4 align-self-center text-center">
                <label class="text-primary">@DURACTION</label>
            </div>
            <div class="col-8">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", id = "Duration", @min = "1" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group text-center m-1" style="float: right">
                <a class="btn btn-success text-white" value="create" onclick="PostCreateAction()">@ADD_TITLE</a>
        </div>
    </div>
}

<script>
    function PostCreateAction() {

        var url = "/Operations/Create";
        var firstEvent = $("#FirstEvent").val();
        var secondEvent = $("#SecondEvent").val();
        var duration = $("#Duration").val();
        $.post(url, { FirstEvent: firstEvent, SecondEvent: secondEvent, Duration: duration }, function (data) {
            if (data.length == 0) {
                $("#myModal").modal("hide");
                $(location).attr('href', "@Url.Action("Index", "Operations")");
            } else {
                $("#myModalBodyDiv").html(data);
            }
        });
    }
</script>

WebApplication1/Views/Operations/Delete.cshtml
@model WebApplication1.Models.Operation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Operation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Operations/Edit.cshtml
@model WebApplication1.Models.Operation
@{

    Layout = "";
    var ACTION_NAME = "Подія";
    var DURACTION = "Тривалість";
    var EDIT_TITLE = "Зберегти";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", id = "id" } })

        <div class="row justify-content-center">
            <div class="col-4 align-self-center text-center">
                <label class="text-primary">@ACTION_NAME</label>
            </div>
            <div class="col-4">
                @Html.EditorFor(model => model.FirstEvent, new { htmlAttributes = new { @class = "form-control", id = "FirstEvent" } })
                @Html.ValidationMessageFor(model => model.FirstEvent, "", new { @class = "text-danger" })
            </div>
            <div class="col-4">
                @Html.EditorFor(model => model.SecondEvent, new { htmlAttributes = new { @class = "form-control", id = "SecondEvent" } })
                @Html.ValidationMessageFor(model => model.SecondEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row justify-content-center mt-1">
            <div class="col-4 align-self-center text-center">
                <label class="text-primary">@DURACTION</label>
            </div>
            <div class="col-8">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", id = "Duration" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group text-center m-1" style="float: right">
            <a class="btn btn-success text-white" value="create" onclick="PostCreateAction()">@EDIT_TITLE</a>
        </div>
    </div>
}

<script>
    function PostCreateAction() {
        var url = "/Operations/Edit";
        var id = $("#Id").val();
        var firstEvent = $("#FirstEvent").val();
        var secondEvent = $("#SecondEvent").val();
        var duration = $("#Duration").val();
        $.post(url, { Id: id, FirstEvent: firstEvent, SecondEvent: secondEvent, Duration: duration }, function (data) {
            if (data.length == 0) {
                $("#myModal").modal("hide");
                $(location).attr('href', "@Url.Action("Index", "Operations")");
            } else {
                $("#myModalBodyDiv").html(data);
            }
        });
    }
</script>

WebApplication1/Views/Operations/Index.cshtml
@model WebApplication1.Models.Operation
@{
    ViewBag.Title = "Home Page";


    var NAME = "Код операції";
    var DURATION = "Тривалість";
    var ACTIONS_BEFORE = "Безпосередньо передуючі операції";
    var ACTIONS_AFTER = "Безпосередньо наступні операції";
    var MODAL_TITLE = "Добавити операцію";
    var CLEAR_ALL_TITLE = "Очистити";
    var GRAPH_TITLE = "Графічне відображення";
    var CALCULATE_TITLE = "Переглянути часові параметри операцій";


    List<WebApplication1.Models.Operation> Operations = new List<WebApplication1.Models.Operation>() { };
    if (ViewBag.Operations != null)
    {
        Operations = ViewBag.Operations;
    }
}
    <div class="row p-4 m-2 justify-content-center">
        <div class="col-lg-12">
            <table class="table text-center table-hover" id="TableValues">
                <thead style="text-align: center">
                    <tr>
                        <th style="display:none"></th>
                        <th scope="col">@NAME</th>
                        <th scope="col">@DURATION</th>
                        <th scope="col">
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Добавити операцію"><i class="fa fa-lg fa-plus-circle m-1" style="color:forestgreen" onclick="AddOperation()"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Очистити все"><i class="fa fa-lg fa-trash-o" style="color:orange" onclick="ClearAll()"></i></a>
                        </th>
                        <th scope="col">
                            <a class="btn btn-outline-success" href="#" data-toggle="tooltip" data-placement="bottom" title="Порахувати" onclick="DrawGraph()">Графік прив'язки</a>
                            <a class="btn btn-outline-success" href="#" data-toggle="tooltip" data-placement="bottom" title="Порахувати" onclick="DrawTable()">Таблиця параметрів часу робіт</a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var o in Operations)
                    {
                        <tr>
                            <td style="display:none">@o.Id</td>
                            <td align="center">
                                (@o.FirstEvent,@o.SecondEvent)
                            </td>
                            <td align="center">
                                @o.Duration
                            </td>
                            <td valign="middle" align="center"></td>
                            <td valign="middle" align="center">
                                <a href="#" style="color: orangered" data-toggle="tooltip" data-placement="bottom" title="Видалити"><i class="fa fa-lg fa-trash" onclick="DeleteOperation(@o.Id)"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<script>
    var ADD_MODAL_TITLE = "Добавити операцію";
    var EDIT_MODAL_TITLE = "Редагування";

    var DrawGraph = function () {
            $(location).attr('href', "@Url.Action("Index", "Graph")");
    }
    var DrawTable = function () {
            $(location).attr('href', "@Url.Action("Index", "Table")");
    }
    var AddOperation = function () {
        $('#ModalTitle').text(function (i, oldText) {
            return ADD_MODAL_TITLE;
        });
        var url = "/Operations/Create/";

        $("#myModalBodyDiv").load(url, function () {
            $("#myModal").modal("show");
        })
    }

    var EditOperation = function (id) {
        $('#ModalTitle').text(function (i, oldText) {
            return EDIT_MODAL_TITLE;
        });
        var url = "/Operations/Edit?id=" + id;

        $("#myModalBodyDiv").load(url, function () {
            $("#myModal").modal("show");
        })
    }

    var ClearAll = function () {
        $.post( "/Operations/ClearAll/", function() {
            $(location).attr('href', "@Url.Action("Index", "Operations")");
        });
    }

    var Calculate = function () {
        $(location).attr('href', "@Url.Action("Index", "Calculation")");
    }

    var DeleteOperation = function (id) {
        var url = "/Operations/Delete?id=" + id;
        $.post(url, function () {
            $(location).attr('href', "@Url.Action("Index", "Operations")");
        });
    }

    var table = $('#TableValues').DataTable();
    $('#TableValues tbody').on('click', 'tr', function () {
        EditOperation(table.row(this).data()[0]);
    });

</script>

WebApplication1/Views/Shared/Footer.cshtml
<footer class="text-center bg-dark text-white">
    <p>&copy; @DateTime.Now.Year - Сіткове моделювання</p>
</footer>

WebApplication1/Views/Shared/Header.cshtml
@{
    var TITLE = "Сіткова модель орієнтована на операції та події";
    var TASK_TITLE = "Задати дані";
}
<div class="navbar navbar-inverse navbar-fixed-top bg-dark text-white">
    <a href="/Home/Index/">@TITLE</a>
    <a href="/Operations/Index/" class="btn btn-success">@TASK_TITLE</a>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/Site.css")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
</head>
<body>

    @RenderPage("../../Modals/ModalViews.cshtml")

    @RenderPage("Header.cshtml")

    <div class="mt-2">
        @RenderBody()
    </div>

    @RenderPage("Footer.cshtml")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>